### ISSUE TITLE
Internal numbering of atoms

### ISSUE THREAD

**Issue by Kloppel** [Kloppel/helpers#6]
The pdb reading functions should be able to keep an internal number count of atoms for very large files, which goes past 99.999. I currently want to add information to a dataframe, where the analysis module from mdanalysis only gives out the numbers of the atoms, but can not because there are more atoms than 99.999 in the files and subsequent atoms are numbered as "*****". This string can not be processed like the other numbers, and for easier automation in practice the reader should update the serial_no entry in the line_dict objects to include the real number the atom would have if it were not for printing the stars. 

In the end it should only print the stars in the end, but for analysis purposes where we loop over the lines, we should add these "internal serial_no's" to the scripting interface. Just keep it out of printing files.

**Comment by Nereumobu** [comment]
Implemented the counter for the serial_no in a new function pdb_tools.files.read_file_dict() from there I also changed some functions down in pdb_tools.operations so they would work in dictionaries directly (the ones that still work in lines are fuse_segments and the split type functions, as it seemed more natural for them).

I tried to run the notebook in the Onedrive but it looks like I lack the "hb_small.npy" file. 

Regarding the residue number, it seems a bit more complex as its choice is up to the one who wrote the pdb file. For example in the water chains of "3hb3_ooxox.pdb" there are multiple lines were consecutive residues in the same chain do not have consecutive residue numbers (for what I have read this is sometimes done to keep with some standards or because the data has been fused from other files). Moreover when a new chain starts the residue number may not restart at 0 (see line 100068 of the aforementioned file).

My idea is that one could keep an absolute numbering of the residues in the file by just counting when the resi_no changes in the pdb. However this numbering will most likely not coincide with the one in the original file (probably diverging quite early).
